### ISSUE TITLE
Sentinel

### ISSUE THREAD

**Issue by reidlai** [ballerina-platform/module-ballerinax-redis#43]
**Description:**
Cannot find connection example using redis sentinel.  How can I specify masterId in connection option?

**Suggested Labels:**
sentinel, masterId

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by kapilraajP** [comment]
Redis sentinel support is currently not there in the Ballerina Redis module

**Comment by abeykoon** [comment]
Moved to : https://github.com/ballerina-platform/ballerina-extended-library/issues/56.
