### ISSUE TITLE
Deployment instruction is obsolete under Ballerina 1.0

### ISSUE THREAD

**Issue by reidlai** [ballerina-platform/module-ballerinax-redis#44]
**Description:**
README.md instruction is obsolete for Ballerina 1.0.  I have no idea can build the module from source and deployed in Ballerina runtime.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abeykoon** [comment]
We have updated Readme.md for Ballerina SLBeta3 version. Please check 
https://github.com/ballerina-platform/module-ballerinax-redis/blob/master/README.md

Feel free to reopen if you have further questions.
