### ISSUE TITLE
Improve module design

### ISSUE THREAD

**Issue by MadhukaHarith92** [ballerina-platform/module-ballerinax-redis#56]
**Description:**
There are 103 operations related to this module and there is only one client for all the 103 actions. When using the Redis module and selecting operations on a client, the user may have to scroll this lengthy set. Hence the user experience might be low.

**Suggested Labels:**
Design/Research

**Suggested Assignees:**
Madhuka

**Affected Product Version:**
0.9.0

**Comment by abeykoon** [comment]
Moved to https://github.com/ballerina-platform/ballerina-extended-library/issues/50
