### ISSUE TITLE
Redis on WS

### ISSUE THREAD

**Issue by AgusRumayor** [ballerina-platform/module-ballerinax-redis#59]
**Description:**
I have no issue working with redis module inside a main function but trying to connect redis in a http service cause the server to never respond ... Here is the code:

import ballerina/http;
import ballerina/log;
import ballerina/redis;
import ballerina/io;

service vqueue on new http:Listener(9090) {
    resource function create(http:Caller caller, http:Request req) returns error? {
        io:println("Redis Service");
        redis:ClientEndpointConfiguration redisConfig = {
        host: "localhost",
        password: "",
        options: { connectionPooling: true, isClusterConnection: false, ssl: false,
            startTls: false, verifyPeer: false, connectionTimeout: 500 }
        };
        redis:Client conn =  check new (redisConfig);
        var result = conn->ping();
        if (result is string) {
            io:println(result);
        } else {
            io:println(result.reason());
        }
        var resp = caller->respond("Hello Redis");
        if (resp is error) {
            log:printError("Error sending response", resp);
        }
    }
}

**Suggested Labels:**
http service, redis, WS

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    
Ubuntu 18, jBallerina 1.2.3
**Steps to reproduce:**
The WS stops working after adding the redis module

**Related Issues:**

**Comment by kapilraajP** [comment]
Redis module can be used within Service as well as follows.
```
import ballerina/http;
import ballerina/log;
import ballerinax/redis;
import ballerina/io;

service / on new http:Listener(9090) {
resource function get create(http:Caller caller, http:Request req) returns error? {
        io:println("Redis Service");
        redis:ClientEndpointConfiguration redisConfig = {
                                                            host: "localhost", password: "",
                                                            options: { connectionPooling: true, isClusterConnection: false, ssl: false,
                                                            startTls: false, verifyPeer: false, connectionTimeout: 500 }
                                                        };
        redis:Client conn = check new (redisConfig);
        var result = conn->ping();
        if (result is string) {
            io:println(result);
        } else {
            io:println(result.toString());
        }
        var resp = caller->respond("Hello Redis");
        if (resp is error) {
            log:printError("Error sending response", resp);
        }
    }
}
```

**Comment by abeykoon** [comment]
Closing as not reproducible as of today.
